# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQXRrrMdUXEotM0yGfEodBsIUvrGXHzu

#Data Science Tools and Ecosystem

## In this notebook Data Science tools and ecosystem are summarized

### Objectives
+ Learn the most common data science languages
+ Learn the most common IDE
+ Learn the data management softwares
+ Understand API´s
+ Learn Data Management tools

### Some of the languages that data scientists commonly use are:
1. Python

2. R

3. Java

4. Scala

5. C++

6. Julia

7. SQL

### Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. Numpy
3. Scikit
4. Keras
5. Tensorflow

| Data Science Tools |
| -------------|
| Jupyter Notebooks |
| R studio |
| Visual Studio |

###Below are a few examples of evaluating arithmetic expressions in Python

1. Multiplication: *
2. Addition: +
3. Substraction: -
4. Division: /

This a simple arithmetic expression to mutiply then add integers
"""

(3*4)+5

"""This will convert 200 minutes to hours by diving by 60"""

minutes = 200
print("Hours",minutes/60, "hours")

"""## Author:

Roman Martinez
"""